version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/runner'
    registries:
      - dockerhub 
    schedule:
      interval: 'monthly'
