name: Push

on:
  push:
    paths:
      - '.github/workflows/push.yml'
      - 'runner/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build
